# Generated by Django 3.1.7 on 2021-10-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('f_link', models.CharField(blank=True, max_length=50, null=True)),
                ('l_lisk', models.CharField(blank=True, max_length=50, null=True)),
                ('t_link', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
