# Generated by Django 3.1.7 on 2021-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0003_employeeteam_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
