# Generated by Django 3.1.7 on 2021-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0004_clients_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='designation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='writer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
