# Generated by Django 3.1.7 on 2021-10-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0005_auto_20211025_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='title',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('size_of_apartment', models.CharField(max_length=50)),
                ('facing', models.CharField(max_length=30)),
                ('basement', models.IntegerField(blank=True, null=True)),
                ('parking', models.IntegerField(blank=True, null=True)),
                ('razuk_no', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='state_app.projectstatus')),
                ('type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='state_app.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('project', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='state_app.projects')),
            ],
        ),
    ]
