# Generated by Django 3.1.7 on 2021-10-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0007_homepageslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
