# Generated by Django 3.1.7 on 2021-10-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0008_projects_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='feature_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
