# Generated by Django 3.1.7 on 2021-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0009_projects_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
