# Generated by Django 3.1.7 on 2021-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0010_projects_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='completed_per',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
