# Generated by Django 3.1.7 on 2021-11-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0012_projectfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_app.projectstatus'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_app.projecttype'),
        ),
    ]
