# Generated by Django 3.1.7 on 2021-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0014_floormap_nearbyinstitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyinstitute',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
