# Generated by Django 3.1.7 on 2021-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0015_nearbyinstitute_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nearbyinstitute',
            name='category',
        ),
    ]
