# Generated by Django 3.1.7 on 2021-11-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_app', '0016_remove_nearbyinstitute_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbyinstitute',
            name='category',
            field=models.CharField(choices=[('S', 'School'), ('H', 'Hospital'), ('E', 'Education'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProjectNearbyInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('S', 'School'), ('H', 'Hospital'), ('E', 'Education'), ('O', 'Other')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='state_app.projects')),
            ],
        ),
    ]
